plugins {
	id "fabric-loom" version "1.7.4"
	id "maven-publish"
}

sourceCompatibility = JavaVersion.VERSION_17
targetCompatibility = JavaVersion.VERSION_17

group = "agency.highlysuspect"
archivesBaseName = "crowmap-1.19.4"
version = "1.1.0"

dependencies {
	minecraft "com.mojang:minecraft:1.19.4"
	mappings loom.officialMojangMappings()
	
	modImplementation "net.fabricmc:fabric-loader:0.16.7"
	modLocalRuntime fabricApi.module("fabric-resource-loader-v0", "0.87.2+1.19.4")
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.encoding = "UTF-8"
}

java {
	withSourcesJar()
}
